DJT/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from DJT import settings
urlpatterns = [
    path('account/', include('apps.account.urls')),
    path('course/', include('apps.course.urls')),
    path('doc/', include('apps.doc.urls')),
    path('admin/', include('apps.admin_staff.urls')),
    path('news/', include('apps.news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# static拼接一个路径列表到原来的列表里面，这样就可以访问media里面的文件了

apps/course/urls.py
from django.urls import path
from .views import *

app_name = 'course'
urlpatterns = [
    path('index/', index_view, name='index_view'),
    path('course/', course, name='course'),
    path('course-detail/<int:course_id>/', course_detail, name='course_detail'),
    path('token/', course_token, name='course_token'),
]

apps/news/urls.py
from django.urls import path
from .views import news_detail, up_token, AddNewsCommentView, comment_new, news_list, news_tag_list, news_with_tag, hot_news_list, NewsBannerView, news_banner_list, searchView

app_name = 'news'
urlpatterns = [
    path('news_detail/<int:news_id>', news_detail, name='news_detail'),
    path('up-token/', up_token, name='up_token'),
    path('add-comment/', AddNewsCommentView.as_view(), name='add_comment'),
    path('comment/', comment_new, name='comment_news'),
    path('list/', news_list, name='news_list'),
    path('tag/list/', news_tag_list, name='news_tag_list'),
    path('news-with-tag/', news_with_tag, name='news_with_tag'),
    path('hot/list/', hot_news_list, name='hot_news_list'),
    path('banner/list/', news_banner_list, name='news_banner_list'),
    path('search/', searchView, name='search'),
]

apps/course/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    # 讲师名
    name = models.CharField(max_length=10)
    # 讲师身份
    identity = models.CharField(max_length=100)
    # 简介
    profile = models.TextField()
    # 头像地址
    avatar_url = models.URLField()
    # 加入时间
    join_date = models.DateTimeField(auto_now_add=True)
    # 是否删除
    is_delete = models.BooleanField(default=False)


class CourseCategory(models.Model):
    # 分类名
    name = models.CharField(max_length=20)
    # 是否删除
    is_delete = models.BooleanField(default=False)


class Course(models.Model):
    # 课程标题
    title = models.CharField(max_length=100)
    # 课程封面图
    cover_url = models.URLField()
    # 课程视频地址
    video_url = models.URLField()
    # 课程时长
    duration = models.FloatField()
    # 课程简介
    profile = models.TextField(null=True, blank=True)
    # 课程大纲
    outline = models.TextField(null=True, blank=True)
    # 创建时间
    create_time = models.DateTimeField(auto_now_add=True)
    # 是否删除
    is_delete = models.BooleanField(default=False)

    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE)

apps/course/views.py
from django.http import Http404, JsonResponse
from django.shortcuts import render
from ..admin_staff.models import NewsTag
from ..news.models import News, NewsHot, NewsBanner
from .models import Course
import os, hmac, hashlib, time
from django.conf import settings



# Create your views here.
# 首页视图
def index_view(request):
    # news = News.objects.defer('content').select_related('tag', 'author').filter(is_delete=0).all()
    # 过滤掉content以及提前查询外健关联的tag、author
    news_tags = NewsTag.objects.filter(is_delete=0).all()
    newses = []
    for tag in news_tags:
        news = News.objects.filter(is_delete=0, tag=tag).all()[0:settings.ONE_PAGE_COUNT]
        if news:
            newses.append(news)
        else:
            newses.append(None)
    banners = NewsBanner.objects.filter(is_delete=False).all()
    h_news = NewsHot.objects.filter(is_delete=False).all()[0: 3]
    return render(request, 'course/index.html', context={
        'news_tags': news_tags,
        'newses': newses,
        'h_news': h_news,
        'banners': banners
    })
# 课程视图
def course(request):
    courses = Course.objects.filter(is_delete=False).all()
    return render(request, 'course/course.html', context={'courses': courses})

# 课程详情也
def course_detail(request, course_id):
    try:
        course = Course.objects.get(id=course_id)
        return render(request, 'course/course_detail.html', context={'course': course})
    except Course.DoesNotExist as info:
        raise Http404


# 百度云视频播放
def course_token(request):
    # 获取视频路径
    video_url = request.GET.get('video_url')
    # video_url = 'http://ih2vvidjmihrie7nvje.exp.bcevod.com/mda-ih6x46pcj8w9vbs1/mda-ih6x46pcj8w9vbs1.m3u8'
    # 过期时间
    expiration_time = int(time.time()) + 3600
    # 百度云 UserId / UserKey
    user_id = settings.BAIDU_CLOUD_USER_ID
    user_key = settings.BAIDU_CLOUD_USER_KEY

    # extension ===> .mu38
    extension = os.path.splitext(video_url)[1]
    # mda-ih6x46pcj8w9vbs1
    media_id = video_url.split('/')[-1].replace(extension, '')

    # key 和 message 转化为 bytes
    key = user_key.encode('utf-8')
    message = '/{0}/{1}'.format(media_id, expiration_time).encode('utf-8')
    # 加密盐 加密数据  加密方式
    signature = hmac.new(key, message, digestmod=hashlib.sha256).hexdigest()
    token = '{0}_{1}_{2}'.format(signature, user_id, expiration_time)
    return JsonResponse({"token": token})

templates/course/course.html
{% extends 'base/base.html' %}
{% block title %}
    课程
{% endblock %}
{% block style_link %}
<link rel="stylesheet" href="/static/css/course/course.css"
{% endblock %}
{% block mid_con %}
    <!--middle start-->
    <div class="middle">
        <div class="mid-top">
            <div class="menu">
                <h3>在线课堂</h3>
                <ul class="title">
                    <li class="activate">创业案例</li>
                    <li>深度报道</li>
                    <li>干货分析</li>
                    <li>投资人说</li>
                </ul>
            </div>
        </div>
        <div class="mid-con">
            <ul class="con-list">
                <li class="con show">
                    <div class="course-list">
                        <ul>
                            {% for course in courses %}
                                <li>
                                <a href="{% url 'course:course_detail' course_id=course.id %}">
                                <img src="{{ course.cover_url }}">
                                </a>
                                <div class="course">
                                    <h3>{{ course.title }}</h3>
                                    <p class="message">{{ course.profile }}</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            {% endfor %}
                            <li>
                                <img src="https://res.shiguangkey.com/file/201803/22/20180322091230008492307.png!mall_course_b">
                                <div class="course">
                                    <h3>大数据</h3>
                                    <p class="message">点燃大数据 引爆人工智能 大数据人工智能课程讲座课程大数据</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com/file/201807/20/20180720164840410880578.jpg!mall_course_b">
                                <div class="course">
                                    <h3>JAVA</h3>
                                    <p class="message">JAVA基础小白的福音，企业级开发入门必会</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="con">
                    <div class="course-list">
                        <ul>
                            <li>
                                <img src="https://res.shiguangkey.com/file/201804/11/20180411175754047081695.jpg!mall_course_b">
                                <div class="course">
                                    <h3>C语言</h3>
                                    <p class="message">从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com//file/201805/05/20180505110937817137153.jpg!mall_course_c">
                                <div class="course">
                                    <h3>1801级中级班(JSJQ)</h3>
                                    <p class="message">从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战</p>
                                    <span class="price">3980元</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com//file/201804/08/20180408230910347931149.png!mall_course_c">
                                <div class="course">
                                    <h3>UI设计</h3>
                                    <p class="message">UI设计零基础到大型项目实战到大型项目实战到大型项目实战</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com/file/201803/22/20180322091230008492307.png!mall_course_b">
                                <div class="course">
                                    <h3>大数据</h3>
                                    <p class="message">点燃大数据 引爆人工智能 大数据人工智能课程讲座课程大数据</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com/file/201807/20/20180720164840410880578.jpg!mall_course_b">
                                <div class="course">
                                    <h3>JAVA</h3>
                                    <p class="message">JAVA基础小白的福音，企业级开发入门必会</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="con">
                    <div class="course-list">
                        <ul>
                            <li>
                                <img src="https://res.shiguangkey.com/file/201804/11/20180411175754047081695.jpg!mall_course_b">
                                <div class="course">
                                    <h3>C语言</h3>
                                    <p class="message">从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com//file/201805/05/20180505110937817137153.jpg!mall_course_c">
                                <div class="course">
                                    <h3>1801级中级班(JSJQ)</h3>
                                    <p class="message">从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战</p>
                                    <span class="price">3980元</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com//file/201804/08/20180408230910347931149.png!mall_course_c">
                                <div class="course">
                                    <h3>UI设计</h3>
                                    <p class="message">UI设计零基础到大型项目实战到大型项目实战到大型项目实战</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com/file/201803/22/20180322091230008492307.png!mall_course_b">
                                <div class="course">
                                    <h3>大数据</h3>
                                    <p class="message">点燃大数据 引爆人工智能 大数据人工智能课程讲座课程大数据</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com/file/201807/20/20180720164840410880578.jpg!mall_course_b">
                                <div class="course">
                                    <h3>JAVA</h3>
                                    <p class="message">JAVA基础小白的福音，企业级开发入门必会</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="con">
                    <div class="course-list">
                        <ul>
                            <li>
                                <img src="https://res.shiguangkey.com/file/201804/11/20180411175754047081695.jpg!mall_course_b">
                                <div class="course">
                                    <h3>C语言</h3>
                                    <p class="message">从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com//file/201805/05/20180505110937817137153.jpg!mall_course_c">
                                <div class="course">
                                    <h3>1801级中级班(JSJQ)</h3>
                                    <p class="message">从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战从基础到项目实战</p>
                                    <span class="price">3980元</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com/file/201807/20/20180720164840410880578.jpg!mall_course_b">
                                <div class="course">
                                    <h3>JAVA</h3>
                                    <p class="message">JAVA基础小白的福音，企业级开发入门必会</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com//file/201804/08/20180408230910347931149.png!mall_course_c">
                                <div class="course">
                                    <h3>UI设计</h3>
                                    <p class="message">UI设计零基础到大型项目实战到大型项目实战到大型项目实战</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                            <li>
                                <img src="https://res.shiguangkey.com/file/201803/22/20180322091230008492307.png!mall_course_b">
                                <div class="course">
                                    <h3>大数据</h3>
                                    <p class="message">点燃大数据 引爆人工智能 大数据人工智能课程讲座课程大数据</p>
                                    <span class="price">免费</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <!--middle end-->
{% endblock %}
{% block script_link %}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="/static/js/course.js"></script>
{% endblock %}

templates/course/course_detail.html
{% extends 'base/base.html' %}

{% block title %}
    {{ course.title }}
{% endblock %}

{% block style_link %}
    <link rel="stylesheet" href="/static/css/course/course_detail.css">
{% endblock %}

{% block mid_con %}
    <!-- main start -->
    <main id="main">
        <div class="w1200">
            <div class="course-contain">
                <div class="course-top-contain">
                    <h4 class="course-title">{{ course.title }}</h4>
                    <div class="course-other clearfix">
                        <div class="share-list">
                            <span>分享至:</span>
                            <i class="PyWhich py-weibo"></i>
                            <i class="PyWhich py-weibo2"></i>
                        </div>
                        <div class="buy-list">
                            <span class="price">免费</span>
                        </div>
                    </div>
                </div>
                <!-- 要一模一样 -->
                <div class="course-video" id="course-video">
                    <span class="course-data" style="display: none;" data-video-url="{{ course.video_url }}"
                          data-cover-url="{{ course.cover_url }}"></span>
                </div>
                <div class="course-bottom-contain clearfix">
                    <div class="course-detail-list">
                        <div class="course-item clearfix">
                            <h5 class="course-title">{{ course.teacher.name }}</h5>
                            <div class="teacher-box clearfix">
                                <img src="{{ course.teacher.avatar_url }}" alt="luweimin" title="luweimin"
                                     class="teacher-avatar">
                                <div class="teacher-info">
                                    <p class="teacher-name">{{ course.teacher.name }}</p>
                                    <p class="teacher-identify"> {{ course.teacher.identity }}</p>
                                </div>
                            </div>
                            <div class="item-content">
                                {{ course.teacher.profile }}
                            </div>
                        </div>
                        <div class="course-item clearfix">
                            <h5 class="course-title">课程简介</h5>
                            <div class="item-content">
                                {{ course.profile }}
                            </div>
                        </div>
                        <div class="course-item clearfix">
                            <h5 class="course-title">课程大纲</h5>
                            <div class="item-content">
                                {{ course.outline|safe }}
                            </div>
                        </div>
                        <div class="course-item clearfix">
                            <h5 class="course-title">帮助中心</h5>
                            <div class="item-content">
                                <p>1. 购买后的课程在线可反复观看学习，视频有效期以具体课程信息为准。 </p>
                                <p>2. 课程暂不支持下载观看，均为在线观看视频。 </p>
                                <p>3. 课程一经购买，不可转让、不可退款；仅限购买账号观看。</p>
                                <p>4. 如有问题请咨询客服: 400-10086-10086 </p>
                            </div>
                        </div>
                        <div class="course-item clearfix">
                            <h5 class="course-title">关于在线课堂</h5>
                            <div class="item-content">
                                在线课堂公司拥有千余人的优秀师资团队，是一家师资丰富、教育产品类别众多的在线培训公司。公司总部座落于美丽的星城长沙，2015年9月正式入驻芯城科技园目前拥有近两万平米办公面积。
                                在线课堂学习的学员已突破1000万人次在线学员覆盖全球，包括中国、加拿大、日本、美国、韩国等诸多国家。
                            </div>
                        </div>
                        <div class="course-item clearfix">
                            <div class="item-content">
                                <div class="item-course-title">123</div>
                                <div class="item-buy-list">
                                    <span class="price">免费</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="course-side">
                        <h4 class="side-title">推荐课程</h4>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- main end -->
{% endblock %}

{% block script_link %}
    <script src="/static/js/course/videojs/video.min.js"></script>
    <script src="/static/js/course/videojs/videojs-contrib-hls.min.js"></script>
    <script src="/static/js/course/videojs/videojs-contrib-quality-levels.min.js"></script>
    <script src="/static/js/course/cyberplayer.js"></script>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="/static/js/course/course_detail.js"></script>
{% endblock %}

templates/course/index.html
{% extends 'base/base.html' %}
{% load new_filter %}
{% block title %}
    首页
{% endblock %}
{% block style_link %}
<link rel="stylesheet" href="/static/css/course/index.css">
{% endblock %}
{% block mid_con %}
    <!--middle start-->
    <div class="middle">
        <div class="mid-con clearfix">
            <div class="con-left">
                <div class="banner">
                    <ul class="photo">
                        {% for photo in banners %}
                            <li><a href="{{ photo.link_to }}"><img src="{{ photo.image_url }}"></a></li>
                        {% endfor %}
                    </ul>
                    <ul class="btn">
                        <li class="left">&lt;</li>
                        <li class="right">&gt;</li>
                    </ul>
                    <ul class="select">
                        {% for photo in banners %}
                            <li></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="news">
                    <ul class="news-list">
                        {% for new in h_news %}
                        <li>
                            <img src="{{ new.news.photo_url }}">
                            <p>{{ new.news.title }}</p>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="menus clearfix">
                    <ul class="title clearfix">
                        {% for tag in news_tags %}
                            <li data-id="{{ tag.id }}" >{{ tag.tag_name }}</li>
                        {% endfor %}
{#                    <li class="activate">{{ tag.tag_name }}</li>#}
                    </ul>
                    <div class="news-contain">
                        <ul class="menus-con clearfix">
                        {% for news in newses %}
                            <li>
                                {% for new in news %}
                                    <div class="info">
                                        <div class="pic">
                                            <img src="{{ new.photo_url }}">
                                        </div>
                                        <div class="text">
                                            <h4><a href="{% url 'news:news_detail' news_id=new.id %}" target="_blank" style="color: #000000;">{{ new.title }}</a></h4>
                                            <p>{{ new.desc }}</p>
                                            <div class="other">
    {#    ======================================数据库表的联级查询 =========================#}
                                                <span class="hot">{{ new.tag.tag_name }}</span>
                                                <span class="time">{{ new.add_time|date_format }}</span>
                                                <span class="author">{{ new.author.username }}</span>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            </li>
                        </ul>
                    </div>
                </div>
                <a href="javascript:void(0)" class="load_multi" data-page="2">加载更多</a>
            </div>
{# =========== con_right  ============= #}
            {% include 'base/con_right.html' %}
        </div>
    </div>
    <!--middle end-->
{% endblock %}
{% block script_link %}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="/static/js/base/common.js"></script>
    <script src="/static/js/index.js"></script>
{% endblock %}