DJT/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from DJT import settings
urlpatterns = [
    path('account/', include('apps.account.urls')),
    path('course/', include('apps.course.urls')),
    path('doc/', include('apps.doc.urls')),
    path('admin/', include('apps.admin_staff.urls')),
    path('news/', include('apps.news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# static拼接一个路径列表到原来的列表里面，这样就可以访问media里面的文件了

apps/account/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, graph_chptcha, sms_send

app_name = 'account'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('loading/', LoginView.as_view(), name='loading'),
    path('out/', LogoutView, name='out_view'),
    path('graph-captcha/', graph_chptcha, name='graph-captcha'),
    path('sms_send/', sms_send, name='sms_send'),
]

apps/admin_staff/urls.py
from django.urls import path
from .views import *
from .course_view import *
from ..news.views import *
from .doc_view import *
from .staff_view import *

app_name = 'admin_staff'
urlpatterns = [
    path('staff/', staff, name='staff'),
    path('news_manage/', NewsTagView.as_view(), name='news_manage'),
    path('newspub/', NewsPUbView.as_view(), name='newspub'),
    path('newsedit/', NewsEditView.as_view(), name='newsedit'),
    path('upload-file/', UploadFile, name='upload_file'),
    path('news-master/', NewsMasterView.as_view(), name='newsmaster'),
    path('news-hot/', NewsHotView.as_view(), name='news_hot'),
    path('news-hot-add/', NewsHotAddView.as_view(), name='news_hot_add'),
    path('news_banner/', NewsBannerView.as_view(), name='news_banner'),
]

# 课堂相关的url
urlpatterns += [
    path('course-pub/', CoursePubView.as_view(), name='course-pub'),
]

# 文档的url
urlpatterns += [
    path('doc_upload/', DocUploadView.as_view(), name='doc_upload'),
]

#权限的url
urlpatterns += [
    path('staff/about/', Staff.as_view(), name="staff_about"),
    path('staff-add/', StaffAdd.as_view(), name="staff_add"),
]

apps/course/urls.py
from django.urls import path
from .views import *

app_name = 'course'
urlpatterns = [
    path('index/', index_view, name='index_view'),
    path('course/', course, name='course'),
    path('course-detail/<int:course_id>/', course_detail, name='course_detail'),
    path('token/', course_token, name='course_token'),
]

apps/doc/urls.py
from django.urls import path
from .views import *

app_name = 'doc'
urlpatterns = [
    path('search/', search, name='search'),
    path('document/', docDownload, name='doc'),
    path('document/download/', download_doc, name='doc_download'),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="/static/css/base/reset.css">
    <link rel="stylesheet" href="/static/css/base/common.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_829410_coh69vo4du7.css">
    {% block style_link %}

    {% endblock %}
</head>
<body>
    <!--top start-->
    <div class="top">
        <div class="top_con">
            <div class="logo"></div>
            <ul class="menu">
                <li class="show"><a href="{% url 'course:index_view' %}">首页</a></li>
                <li><a href="{% url 'course:course' %}">在线课堂</a></li>
                <li><a href="{% url 'doc:doc' %}">文档下载</a></li>
                <li><a href="{% url 'doc:search' %}">搜索</a></li>

            </ul>
            <div class="load">
                {#判断用户是否登陆#}
                {% if user.is_authenticated %}
                    <!-- logged start -->
                    <div class="author">
                        <i class="iconfont icon-user"></i>
                        <span>{{ user.username }}</span>
                        <ul class="author-menu">
                            {#判断用户是否是员工#}
                            {% if user.is_staff %}
                                <li><a href="{% url 'admin_staff:staff' %}">后台管理</a></li>
                            {% endif %}
                            <li><a href="{% url 'account:out_view' %}">退出登录</a></li>
                        </ul>
                    </div>
                    <!-- loged end -->
                {% else %}
                    <i class="iconfont icon-user"></i>
                    <a href="{% url 'account:register' %}">注册</a>
                    /
                    <a href="{% url 'account:register' %}">登陆</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!--top end-->
    <!--middle start-->
    <div class="middle">
            {% block mid_con %}

            {% endblock %}
    </div>
    <!--middle end-->
    <!--bottom start-->
    <div class="bottom">
        <div class="bot1">
            <div class="bot_con">
                <div class="logo"></div>
                <p class="link-on">
                    <span class="link"><a href="javascript:void(0)">人生苦短 |</a></span>
                    <span class="link"><a href="javascript:void(0)">我用python |</a></span>
                    <span class="link"><a href="javascript:void(0)">举杯邀明月 |</a></span>
                    <span class="link"><a href="javascript:void(0)">对影成三人 |</a></span>
                    <span class="link"><a href="javascript:void(0)">但愿人长久 |</a></span>
                    <span class="link"><a href="javascript:void(0)">千里共婵娟 |</a></span>
                    <span class="about-me"><a href="javascript:void(0)">
                        <i class="iconfont icon-wechat"></i>卢伟民</a></span>
                </p>
                <p class="address">
                    <span class="addr">地址：中华人民共和国广东省广州市</span>
                    <span class="tel">电话：400-10086-10086</span>
                </p>
            </div>
        </div>
        <div class="bot2">
            <div class="bot_con">
                <p>Copyright &copy; 2017 All Rights Reserved</p>
            </div>
        </div>
    </div>
    <!--bottom end-->
    {% block script_link %}

    {% endblock %}
</body>
</html>

templates/base/con_right.html
<div class="con-right">
    <div class="offline-class">
        <h3>线下课程<a href="javascript:void(0);">更多</a></h3>
        <div class="pic">
            <img src="https://res.shiguangkey.com//file/201808/18/20180818153301380874592.jpg!mall_course_c">
            <p>第九艺术公开课</p>
        </div>
        <ul class="status">
            <li>
                <a href="javascript:void(0);">
                    <span class="starting">报名中</span><span>游戏开发基础班</span>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <span class="ending">已结束</span><span>日语班</span>
                </a>
            </li>
        </ul>
    </div>
    <div class="online-class">
        <h3>线上课程<a href="javascript:void(0);">更多</a></h3>
        <div class="pic">
            <img src="https://res.shiguangkey.com//file/201807/18/20180718165748968957414.png!mall_course_c">
            <p>游戏原画绘画学习</p>
        </div>
        <ul class="status">
            <li>
                <a href="javascript:void(0);">
                    <span class="starting">报名中</span><span>C++基础班班</span>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <span class="ending">已结束</span><span>python班</span>
                </a>
            </li>
        </ul>
    </div>
    <div class="attention-me clearfix">
        <h3>关注我</h3>
        <ul class="info">
            <li><i class="iconfont icon-qq" style="color: deepskyblue;"></i>1078861774</li>
            <li><i class="iconfont icon-github" style="color: gray;"></i>luweimin</li>
            <li><i class="iconfont icon-weibo" style="color: red;"></i>卢伟民</li>
        </ul>
        <div class="attention">
            <p>扫码关注</p>
        </div>
    </div>
    <div class="hot-recommend">
        <h3>热点推荐</h3>
        <ul class="hot-news">
            <li class="clearfix">
                <div class="news-con">
                    <p>英雄联盟S8入围赛黑马战队合集 英雄联盟S8入围赛黑马战队合集</p>
                    <div class="other">
                        <span class="hot">热点</span>
                        <span class="time">9月30日</span>
                    </div>
                </div>
                <div class="pic"><img src="http://img1.gtimg.com/21/2147/214746/21474698_small.jpg"></div>
            </li>
            <li class="clearfix">
                <div class="news-con">
                    <p>港珠澳大桥开展三地联合试运行 40分钟驶完全程</p>
                    <div class="other">
                        <span class="hot">热点</span>
                        <span class="time">9月30日</span>
                    </div>
                </div>
                <div class="pic"><img src="http://inews.gtimg.com/newsapp_ls/0/5564903996_150120/0"></div>
            </li>
            <li class="clearfix">
                <div class="news-con">
                    <p>新思维、新路径、新挑战，5G到底应该怎么做？ 新思维、新路径、新挑战，5G到底应该怎么做？</p>
                    <div class="other">
                        <span class="hot">热点</span>
                        <span class="time">9月30日</span>
                    </div>
                </div>
                <div class="pic"><img src="https://inews.gtimg.com/newsapp_ls/0/5566234334_294195/0"></div>
            </li>
        </ul>
    </div>
</div>