DJT/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from DJT import settings
urlpatterns = [
    path('account/', include('apps.account.urls')),
    path('course/', include('apps.course.urls')),
    path('doc/', include('apps.doc.urls')),
    path('admin/', include('apps.admin_staff.urls')),
    path('news/', include('apps.news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# static拼接一个路径列表到原来的列表里面，这样就可以访问media里面的文件了

apps/admin_staff/urls.py
from django.urls import path
from .views import *
from .course_view import *
from ..news.views import *
from .doc_view import *
from .staff_view import *

app_name = 'admin_staff'
urlpatterns = [
    path('staff/', staff, name='staff'),
    path('news_manage/', NewsTagView.as_view(), name='news_manage'),
    path('newspub/', NewsPUbView.as_view(), name='newspub'),
    path('newsedit/', NewsEditView.as_view(), name='newsedit'),
    path('upload-file/', UploadFile, name='upload_file'),
    path('news-master/', NewsMasterView.as_view(), name='newsmaster'),
    path('news-hot/', NewsHotView.as_view(), name='news_hot'),
    path('news-hot-add/', NewsHotAddView.as_view(), name='news_hot_add'),
    path('news_banner/', NewsBannerView.as_view(), name='news_banner'),
]

# 课堂相关的url
urlpatterns += [
    path('course-pub/', CoursePubView.as_view(), name='course-pub'),
]

# 文档的url
urlpatterns += [
    path('doc_upload/', DocUploadView.as_view(), name='doc_upload'),
]

#权限的url
urlpatterns += [
    path('staff/about/', Staff.as_view(), name="staff_about"),
    path('staff-add/', StaffAdd.as_view(), name="staff_add"),
]

apps/admin_staff/models.py
from django.db import models

# Create your models here.
class NewsTag(models.Model):

    tag_name = models.CharField(max_length=20)
    create_time = models.DateTimeField(auto_now_add=True)
    # 假删
    is_delete = models.BooleanField(default=False)

apps/admin_staff/forms.py
from django import forms
from apps.forms import FormMixin
from apps.doc.models import Doc


class CoursePubForm(forms.Form, FormMixin):
    category_id = forms.IntegerField(error_messages={"required": "课程id错误"})
    teacher_id = forms.IntegerField(error_messages={"required": "讲师id错误"})
    title = forms.CharField(error_messages={"required": "新闻标题错误"})
    cover_url = forms.URLField(error_messages={"required": "课程封面", "invalid": "课程封面地址不合法"})
    video_url = forms.URLField(error_messages={"required": "课程视频不能为空", "invalid": "视频地址不合法"})
    duration = forms.IntegerField(error_messages={"required": "课程时长不能为空"})
    profile = forms.CharField(error_messages={"required": "课程简介不能为空"})
    outline = forms.CharField(error_messages={"required": "课程大纲不能为空"})


# 和models.serialize一样直接对读模型的字段验证
class DocUploadForm(forms.ModelForm, FormMixin):
    class Meta:
        model = Doc
        fields = '__all__'
        error_messages = {
            "file_path": {
                "required": "文件路径不能为空"
            },
            "title": {
                "required": "文档标题不能为空"
            }
        }

apps/admin_staff/views.py
from django.http import QueryDict
from django.shortcuts import render
from django.views import View
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from utils import json_status
from utils.Mydecorators import user_permission_required
from .models import NewsTag
from ..news.models import News
from django.core.paginator import Paginator
from datetime import datetime, timedelta
from DJT import settings
from urllib.parse import urlencode
from django.utils.timezone import make_aware
from ..news.forms import NewsHotAddForm, NewsEditForm
from ..news.models import NewsHot


# Create your views here.
def staff(request):
    return render(request, 'admin_staff/index/index.html')


# 装饰器去掉跨域验证，检验是否是员工账号登陆，不是的话去到登陆页面，next=管理页面
@method_decorator([csrf_exempt, staff_member_required(login_url='/account/loading/')], name='dispatch')
class NewsTagView(View):
    def get(self, request):
        news_tag = NewsTag.objects.filter(is_delete=False).all()
        return render(request, 'admin_staff/news/news_manage.html', context={'news_tag': news_tag, })

    # 新增标签
    def post(self, request):
        name = request.POST.get('name')
        if name.strip():
            # exists存在就返回true不存在就返回false
            tag_exists = NewsTag.objects.filter(tag_name=name).exists()
            if tag_exists:
                return json_status.params_error('标签已存在')
            else:
                NewsTag.objects.create(tag_name=name)
                return json_status.ok()
        else:
            return json_status.params_error('标签已存在')

    # 修改、编辑标签
    def put(self, request):
        # request的内容都在body里面，把body转换为query字典
        result = QueryDict(request.body)
        tag_name = result.get('tag_name')
        tag_id = result.get('tag_id')
        if tag_name and tag_id:
            tag = NewsTag.objects.filter(tag_name=tag_name).exists()
            if tag:
                return json_status.params_error('标签已存在')
            else:
                tag = NewsTag.objects.filter(id=tag_id)
                tag.update(tag_name=tag_name)
                return json_status.result()
        else:
            return json_status.params_error('请输入正确标签')

    # 删除标签
    def delete(self, request):
        result = QueryDict(request.body)
        tag_id = result.get('tag_id')
        tag = NewsTag.objects.filter(id=tag_id)
        if tag:
            tag.update(is_delete=True)
            return json_status.ok()
        else:
            return json_status.params_error('标签已删除或不存在')


# 新闻管理
@method_decorator([csrf_exempt, ], name='dispatch')
class NewsMasterView(View):
    def get(self, request):
        newses = News.objects.defer('content').select_related('tag', 'author').filter(is_delete=False)
        p = int(request.GET.get('p', 1))
        start_time = request.GET.get('start_time', '')
        end_time = request.GET.get('end_time', '')
        title = request.GET.get('title', '')
        author = request.GET.get('author', '')
        tag_id = request.GET.get('tag_id', 0)
        # 后台返回新闻标题到前端，避免每次点击查询时候标签栏都会清空

        if start_time and end_time:
            start_time_1 = datetime.strptime(start_time, '%Y/%m/%d')
            end_time_1 = datetime.strptime(end_time, '%Y/%m/%d') + timedelta(days=1)
            # make_aware消除时区设置后的报错问题
            newses = newses.filter(add_time__range=(make_aware(start_time_1), make_aware(end_time_1)))
        if title:
            # contains。。。包含title
            newses = newses.filter(title__icontains=title)
        if author:
            newses = newses.filter(author__username__icontains=author)
        if int(tag_id) > 0:
            newses = newses.filter(tag_id=tag_id)
        # 分页，每页2条新闻
        one_page_news = Paginator(newses, settings.ONE_PAGE_COUNT)
        # 返回第p页的新闻，pages.object_list新闻数据
        pages = one_page_news.page(p)
        news_tag = NewsTag.objects.filter(is_delete=False).all()
        context = {'newses': pages.object_list,
                   'news_tag': news_tag,
                   'page': pages,
                   'paginator': one_page_news,
                   'start_time': start_time,
                   'end_time': end_time,
                   'title': title,
                   'author': author,
                   'tag_id': int(tag_id),
                   'url_param': urlencode({  # urlecode把参数转化为key=value的形式
                       'start_time': start_time,
                       'end_time': end_time,
                       'title': title,
                       'author': author,
                       'tag_id': tag_id,
                   })
                   }
        page_data = NewsMasterView.get_page_data(one_page_news, pages)
        context.update(page_data)
        return render(request, 'admin_staff/news/news_master.html', context=context)

    # 静态方法，相当于全局函数，不用实例化就可以调用，调用时候不会自动把实例传给方法，因为没有self
    # 分页优化
    @staticmethod
    def get_page_data(paginator, page, around_count=2):
        # 当前页码
        current_page = page.number
        # 总页数
        total_page = paginator.num_pages

        left_has_more = False
        right_has_more = False
        # 左边页码区间
        left_start_index = current_page - around_count
        left_end_index = current_page

        if current_page < around_count + around_count + 1:
            left_page = range(1, left_end_index)
        else:
            left_has_more = True
            left_page = range(left_start_index, left_end_index)
        # 右边页码区间
        right_start_index = current_page + 1
        right_end_index = current_page + around_count + 1
        if current_page >= total_page - around_count - 1:
            right_page = range(right_start_index, total_page + 1)
        else:
            right_has_more = True
            right_page = range(right_start_index, right_end_index)

        return {'current_page': current_page,
                'total_page': total_page,
                'left_has_more': left_has_more,
                'left_page': left_page,
                'right_has_more': right_has_more,
                'right_page': right_page
                }

    # 删除新闻
    def delete(self, request):
        from django.http import QueryDict
        res = QueryDict(request.body)
        news_id = res.get('news_id')
        if news_id:
            news = News.objects.filter(id=news_id).first()
            if news:
                hot_news = NewsHot.objects.filter(news=news)
                if hot_news:
                    hot_news.update(is_delete=True)
                news.is_delete = True
                news.save()
                return json_status.result()
            return json_status.params_error(message="新闻不存在")
        return json_status.params_error(message="参数错误")


# 热门新闻管理，编辑和删除
@method_decorator(csrf_exempt, name='dispatch')
class NewsHotView(View):
    def get(self, request):
        return render(request, 'news/news_hot.html')

    def put(self, request):
        ret = QueryDict(request.body)
        priority = int(ret.get('priority', 0))
        if priority:
            hot_news_id = int(ret.get('hot_news_id', 0))
            hot_news = NewsHot.objects.filter(id=hot_news_id)
            if hot_news:
                hot_news.update(priority=priority)
                return json_status.result()
            else:
                return json_status.params_error(message='热门新闻不存在')
        return json_status.params_error(message='热门新闻不存在')

    def delete(self, request):
        ret = QueryDict(request.body)
        # print(ret) < QueryDict: {'hot_news_id': ['1']} >
        hot_news_id = int(ret.get('hot_news_id', 0))
        if hot_news_id:
            hot_news = NewsHot.objects.filter(id=hot_news_id)
            if hot_news:
                hot_news.update(is_delete=True)
                return json_status.result()
            else:
                return json_status.params_error(message='热门新闻不存在')
        else:
            return json_status.params_error(message='热门新闻不存在')


# 热门新闻添加
@method_decorator(csrf_exempt, name='dispatch')
class NewsHotAddView(View):
    def get(self, request):
        return render(request, 'news/news_hot_add.html')

    def post(self, request):
        form = NewsHotAddForm(request.POST)
        if form.is_valid():
            news_id = form.cleaned_data.get('news_id')
            priority = form.cleaned_data.get('priority')
            news = News.objects.filter(id=news_id).first()
            if news:
                hot_news = NewsHot.objects.filter(news=news).exists()
                if hot_news:
                    return json_status.params_error(message='热门新闻已存在')
                NewsHot.objects.create(priority=priority, news=news)
                return json_status.result()
            return json_status.params_error(message='新闻不存在')
        else:
            return json_status.params_error(message=form.get_error())


# 新闻编辑
@method_decorator(csrf_exempt, name='dispatch')
class NewsEditView(View):
    def get(self, request):
        news_id = request.GET.get('news_id')
        if news_id:
            news = News.objects.filter(id=news_id).first()
            if news:
                tags = NewsTag.objects.filter(is_delete=False).all()
                return render(request, 'news/newspub.html', context={'news': news, 'tags': tags})
            return json_status.params_error(message='新闻不存在或者已删除')
        return json_status.params_error(message='新闻id不正确')

    def post(self, request):
        form = NewsEditForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            tag_id = form.cleaned_data.get('tag_id')
            photo_url = form.cleaned_data.get('photo_url')
            content = form.cleaned_data.get('content')
            news_id = form.cleaned_data.get('news_id')
            news = News.objects.filter(id=news_id, is_delete=False)

templates/admin_staff/base/admin_base.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="/static/css/admin_staff/base/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/static/css/admin_staff/base/font-awesome.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/css/admin_staff/base/AdminLTE.min.css">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
    <link rel="stylesheet" href="/static/css/admin_staff/base/skin-green.css">
    {% block style_link %}

    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-green sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="http://127.0.0.1:8000/course/index/" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>P</b>y</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account Menu -->
          <!-- 用户菜单 -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="/static/img/user2-160x160.jpg" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <!-- 用户名 -->
              <span class="hidden-xs">{{ user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="/static/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                <p>
                    帅气的小伙子
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">个人详情</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">退出登录</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/static/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p style="line-height: 2; font-size: 20px;">{{ user.username }}</p>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">头部</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="active"><a href="{% url 'admin_staff:staff' %}"><i class="fa fa-home"></i> <span>首页</span></a></li>
        <li class="header">新闻</li>
        <li class="active"><a href="{% url 'admin_staff:news_manage' %}"><i class="fa fa-tags"></i> <span>新闻标签管理</span></a></li>
        <li class="active"><a href="{% url 'admin_staff:newspub' %}"><i class="fa fa-plus"></i> <span>新闻发布管理</span></a></li>
        <li class="active"><a href="{% url 'admin_staff:newsmaster' %}"><i class="fa fa-cc-mastercard"></i> <span>新闻管理</span></a></li>
        <li class="active"><a href="{% url 'admin_staff:news_hot' %}"><i class="fa fa-file"></i> <span>热门新闻管理</span></a></li>
        <li class="active"><a href="{% url 'admin_staff:news_hot_add' %}"><i class="fa fa-cloud-upload"></i> <span>热门新闻发布</span></a></li>
        <li class="active"><a href="{% url 'admin_staff:news_banner' %}"><i class="fa fa-image"></i> <span>轮播图管理</span></a></li>
        <li class="header">课程</li>
        <li class="active"><a href="{% url 'admin_staff:course-pub' %}"><i class="fa fa-video-camera"></i> <span>课程发布</span></a></li>
        <li class="header">文档</li>
        <li class="active"><a href="{% url 'admin_staff:doc_upload' %}"><i class="fa fa-upload"></i> <span>文档管理</span></a></li>
          {% if user.is_superuser %}
        <li class="header">员工</li>
        <li class="active"><a href="{% url 'admin_staff:staff_about' %}"><i class="fa fa-upload"></i> <span>员工档管理</span></a></li>
          {% endif %}
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {% block heard %}{% endblock %}
      </h1>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

        {% block content %}
        {% endblock %}

      <!--------------------------
        | Your Page Content Here |
        -------------------------->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="/static/js/admin_staff/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/static/js/admin_staff/bootstrap.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/js/admin_staff/adminlte.min.js"></script>
{% block script_link %}{% endblock %}
<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>