DJT/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from DJT import settings
urlpatterns = [
    path('account/', include('apps.account.urls')),
    path('course/', include('apps.course.urls')),
    path('doc/', include('apps.doc.urls')),
    path('admin/', include('apps.admin_staff.urls')),
    path('news/', include('apps.news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# static拼接一个路径列表到原来的列表里面，这样就可以访问media里面的文件了

apps/admin_staff/urls.py
from django.urls import path
from .views import *
from .course_view import *
from ..news.views import *
from .doc_view import *
from .staff_view import *

app_name = 'admin_staff'
urlpatterns = [
    path('staff/', staff, name='staff'),
    path('news_manage/', NewsTagView.as_view(), name='news_manage'),
    path('newspub/', NewsPUbView.as_view(), name='newspub'),
    path('newsedit/', NewsEditView.as_view(), name='newsedit'),
    path('upload-file/', UploadFile, name='upload_file'),
    path('news-master/', NewsMasterView.as_view(), name='newsmaster'),
    path('news-hot/', NewsHotView.as_view(), name='news_hot'),
    path('news-hot-add/', NewsHotAddView.as_view(), name='news_hot_add'),
    path('news_banner/', NewsBannerView.as_view(), name='news_banner'),
]

# 课堂相关的url
urlpatterns += [
    path('course-pub/', CoursePubView.as_view(), name='course-pub'),
]

# 文档的url
urlpatterns += [
    path('doc_upload/', DocUploadView.as_view(), name='doc_upload'),
]

#权限的url
urlpatterns += [
    path('staff/about/', Staff.as_view(), name="staff_about"),
    path('staff-add/', StaffAdd.as_view(), name="staff_add"),
]

apps/news/urls.py
from django.urls import path
from .views import news_detail, up_token, AddNewsCommentView, comment_new, news_list, news_tag_list, news_with_tag, hot_news_list, NewsBannerView, news_banner_list, searchView

app_name = 'news'
urlpatterns = [
    path('news_detail/<int:news_id>', news_detail, name='news_detail'),
    path('up-token/', up_token, name='up_token'),
    path('add-comment/', AddNewsCommentView.as_view(), name='add_comment'),
    path('comment/', comment_new, name='comment_news'),
    path('list/', news_list, name='news_list'),
    path('tag/list/', news_tag_list, name='news_tag_list'),
    path('news-with-tag/', news_with_tag, name='news_with_tag'),
    path('hot/list/', hot_news_list, name='hot_news_list'),
    path('banner/list/', news_banner_list, name='news_banner_list'),
    path('search/', searchView, name='search'),
]

apps/news/models.py
from django.db import models


# Create your models here.
# 新闻模型表
class News(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=200)
    # 保存图片的url地址
    photo_url = models.URLField()
    content = models.TextField()
    add_time = models.DateTimeField(auto_now_add=True)
    is_delete = models.BooleanField(default=False)
    # on_delete级连删除
    tag = models.ForeignKey('admin_staff.NewsTag', on_delete=models.CASCADE)
    author = models.ForeignKey('account.User', on_delete=models.CASCADE)

    # 设置按-id排序，filter查询出来的结果就是倒序的
    # 或者在filter后面加order_by（'-id'）
    class Meta:
        ordering = ('-id',)


# 新闻评论模型表
class NewsComment(models.Model):
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    is_delete = models.BooleanField(default=False)
    author = models.ForeignKey('account.User', on_delete=models.CASCADE)
    # News反向查询的话就是comment or NewsComment_set
    news = models.ForeignKey('News', on_delete=models.CASCADE, related_name='comment')

    class Meta:
        ordering = ('-id',)


class NewsHot(models.Model):
    # 和新闻表是一对一关系
    news = models.OneToOneField('News', on_delete=models.CASCADE)
    # 优先级
    priority = models.IntegerField()
    is_delete = models.BooleanField(default=False)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-priority',)


class NewsBanner(models.Model):
    image_url = models.URLField()
    priority = models.IntegerField()
    link_to = models.URLField()
    create_date = models.DateTimeField(auto_now_add=True)
    is_delete = models.BooleanField(default=False)

    class Meta:
        ordering = ['-priority']

apps/news/forms.py
from django import forms
from apps.forms import FormMixin


# 提交新闻form验证表单
class NewsPubForm(forms.Form, FormMixin):
    title = forms.CharField(max_length=100, min_length=2,
                            error_messages={'required': '新闻标题不能为空', 'max_length': '新闻标题字数不能大于100'})
    desc = forms.CharField(max_length=200, min_length=2,
                           error_messages={'required': '新闻标题不能为空', 'max_length': '新闻标题字数不能大于200'})
    tag_id = forms.IntegerField(error_messages={'required': 'ID不能为空'})
    photo_url = forms.CharField(error_messages={'required': '图片不能为空'})
    content = forms.CharField(max_length=10000, min_length=2,
                              error_messages={'required': '新闻内容不能为空', 'max_length': '内容不能超过10000'})


class AddNewsCommentForm(forms.Form, FormMixin):
    news_id = forms.IntegerField(error_messages={'required': '新闻id不能为空'})
    content = forms.CharField(error_messages={'required': '评论不能为空'})


class NewsHotAddForm(forms.Form, FormMixin):
    news_id = forms.IntegerField(error_messages={'required': '参数错误'})
    priority = forms.IntegerField(error_messages={'required': '优先级不能为空'})


class NewsEditForm(NewsPubForm):
    news_id = forms.IntegerField(error_messages={'required': '新闻ID错误'})


class NewsBannerForm(forms.Form, FormMixin):
    image_url = forms.URLField(error_messages={'required': '图片地址不能为空', 'invalid': '请输入合法网址'})
    priority = forms.IntegerField(error_messages={'required': '优先级不能为空'})
    link_to = forms.URLField(error_messages={'required': '跳转地址不能为空', 'invalid': '请输入合法网址'})

apps/news/views.py
from django.db.models import Q
from django.http import JsonResponse, QueryDict
from django.shortcuts import render, Http404
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.views.decorators.http import require_GET
from utils import json_status
import os
from DJT import settings
from .forms import NewsPubForm, AddNewsCommentForm, NewsBannerForm
from ..admin_staff.models import NewsTag
from .models import News
from qiniu import Auth
from .models import NewsComment, NewsHot, NewsBanner
from .serializers import NewsCommentSerializers, NewsSerializers, NesTagSerializers, NewsHotSerializer, \
    NewsBannerSerializer
from utils.Mydecorators import ajax_login_reruired
from utils.Mydecorators import user_permission_required


# 发布新闻页面
@method_decorator([csrf_exempt, staff_member_required(login_url='/account/loading/')], name='dispatch')
class NewsPUbView(View):
    def get(self, request):
        tags = NewsTag.objects.filter(is_delete=0).all()
        return render(request, 'news/newspub.html', context={'tags': tags})

    def post(self, request):
        form = NewsPubForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            tag_id = form.cleaned_data.get('tag_id')
            photo_url = form.cleaned_data.get('photo_url')
            content = form.cleaned_data.get('content')
            tag = NewsTag.objects.filter(id=tag_id).first()
            if tag:
                News.objects.create(title=title, desc=desc, tag=tag, photo_url=photo_url, content=content,
                                    author=request.user)
                return json_status.result()
        else:
            return json_status.params_error(message=form.get_error())


# 上传文件
@csrf_exempt
@user_permission_required(NewsBanner)
def UploadFile(request):
    file = request.FILES.get('upload_file')
    file_name = file.name
    file_path = os.path.join(settings.MEDIA_ROOT, file_name)
    print(file)
    with open(file_path, 'wb') as data:
        # chunks 返回一个生成器
        for chunk in file.chunks():
            data.write(chunk)
    # 返回当前视图的绝对路径http://127.0.0.1:8000/admin/upload-file/
    # http: // 127.0.0.1: 8000 / Users / luweimin / PycharmProjects / DJT / mediacode.md
    file_url = request.build_absolute_uri(settings.MEDIA_URL + file_name)
    return json_status.result(data={'file_url': file_url})


# 上传图片到七牛

def up_token(request):
    # 需要填写你的 Access Key 和 Secret Key
    access_key = settings.QINIU_AK
    secret_key = settings.QINIU_SK
    # 构建鉴权对象
    q = Auth(access_key, secret_key)
    # 要上传的空间
    bucket_name = 'luweimin'

    # 生成上传 Token，可以指定过期时间等
    token = q.upload_token(bucket_name)
    return JsonResponse({'uptoken': token})


# 新闻详情页面
def news_detail(request, news_id):
    # news = News.objects.filter(id=news_id, is_delete=0).first()
    # return render(request, 'news/news_detail.html', context={'news': news, })
    try:
        news = News.objects.get(id=news_id, is_delete=0)
        return render(request, 'news/news_detail.html', context={'news': news, })
    except News.DoesNotExist:
        # 页面不存在或者说找不到新闻，http404错误,只能debug=false才能用
        raise Http404


# 添加新闻评论
@method_decorator([csrf_exempt, ajax_login_reruired], name='dispatch')
class AddNewsCommentView(View):
    def post(self, request):
        form = AddNewsCommentForm(request.POST)
        if form.is_valid():
            news_id = form.cleaned_data.get('news_id')
            content = form.cleaned_data.get('content')
            news = News.objects.filter(id=news_id, ).first()
            if news:
                comment = NewsComment.objects.create(content=content, author=request.user, news=news)
                serializers = NewsCommentSerializers(comment)
                return json_status.result(data=serializers.data)
            else:
                return json_status.params_error('新闻不存在或已删除')
        else:
            return json_status.params_error(message='评论失败')


# 新闻评论列表
def comment_new(request):
    news_id = request.GET.get('news_id')
    news = News.objects.filter(id=news_id).first()
    if news:
        # news.newscomment_set反向查询
        news_comment = news.comment.all()
        # comments = list(news_comment.values())
        # 序列化查询结果，自动序列化关联的表
        serializers = NewsCommentSerializers(news_comment, many=True)
        # print(type(serializers))<class 'rest_framework.serializers.ListSerializer'>  ListSerializer
        # print(type(serializers.data))<class 'rest_framework.utils.serializer_helpers.ReturnList'>   JsonSerializer
        return json_status.result(data=serializers.data)
    else:
        return json_status.params_error(message='新闻不存在')


def news_list(request):
    tag_id = request.GET.get('tag_id')
    page = int(request.GET.get('page', 1))
    start_page = settings.ONE_PAGE_COUNT * (page - 1)
    end_page = start_page + settings.ONE_PAGE_COUNT
    newses = News.objects.defer('content').select_related('tag', 'author').filter(is_delete=0, tag_id=tag_id).all()[
             start_page: end_page]
    if tag_id:
        return json_status.result(data={'newses': NewsSerializers(newses, many=True).data})
    else:
        return json_status.params_error(message='新闻不存在')


# 返回api接口  /news/tag/list/
def news_tag_list(request):
    news_tags = NewsTag.objects.filter(is_delete=False).all()
    serizlizer = NesTagSerializers(news_tags, many=True)
    return json_status.result(data={'tags': serizlizer.data})


# 返回新闻和标签
def news_with_tag(request):
    tag_id = int(request.GET.get('tag_id', 0))
    if tag_id:
        newses = News.objects.filter(is_delete=False, tag=tag_id)
    else:
        newses = News.objects.filter(is_delete=False)
    serizlizer = NewsSerializers(newses, many=True)
    return json_status.result(data={'newses': serizlizer.data})


# 返回热门新闻列表
def hot_news_list(request):
    hot_news = NewsHot.objects.filter(is_delete=False)
    serializers = NewsHotSerializer(hot_news, many=True)
    return json_status.result(data=serializers.data)


# 轮播图的增删改
@method_decorator([csrf_exempt, ], name='dispatch')
class NewsBannerView(View):
    def get(self, request):
        return render(request, 'admin_staff/news/news_banner.html')

    def post(self, request):
        form = NewsBannerForm(request.POST)
        if form.is_valid():
            link_to = form.cleaned_data.get("link_to")
            image_url = form.cleaned_data.get('image_url')
            priority = form.cleaned_data.get('priority')
            print('link_to:{},image_url:{},priority:{} '.format(link_to, image_url, priority))
            banner = NewsBanner.objects.create(image_url=image_url, priority=priority, link_to=link_to)
            return json_status.result(data={"banner_id": banner.id})
        return json_status.params_error(message=form.get_error())

    def put(self, request):
        p = QueryDict(request.body)
        banner_id = p.get("banner_id")
        image_url = p.get("image_url")
        priority = p.get("priority")
        link_to = p.get("link_to")
        if banner_id:
            banner = NewsBanner.objects.filter(id=banner_id)
            if banner:
                banner.update(image_url=image_url, priority=priority, link_to=link_to)
                return json_status.result()
            return json_status.result().params_error(message='轮播图找不到')
        return json_status.result().params_error(message="bannerId不存在")

    def delete(self, request):
        d = QueryDict(request.body)
        banner_id = d.get("banner_id")
        if banner_id:
            banner = NewsBanner.objects.filter(id=banner_id)
            if banner:
                banner.update(is_delete=True)
                return json_status.result()
            return json_status.params_error(message="轮播图不存在")
        return json_status.params_error(message="轮播图id不存在")


@require_GET  # /news/banner/list/
def news_banner_list(request):
    """返回banner的列表 """
    banners = NewsBanner.objects.filter(is_delete=False)
    serializer = NewsBannerSerializer(banners, many=True)
    return json_status.result(data={"banners": serializer.data})

# 搜索视图
def searchView(request):
    q = request.GET.get('q', '')
    if q:
        ret_newses = News.objects.filter(
            Q(title__contains=q) | Q(content__icontains=q) | Q(author__username__icontains=q))
        context = {'ret_newses': ret_newses,
                   'q': q}
    else:
        hot_newses = NewsHot.objects.filter(is_delete=False).all()
        context = {'hot_newses': hot_newses}

    return render(request, 'news/search.html', context=context)

templates/news/index.html
{% extends 'base/front_base.html' %}

{% block title %}
  首页
{% endblock %}

{% block link %}
	<link rel="stylesheet" href="/static/css/news/index.css">
{% endblock %}

{% block main %}
	<!-- main start -->
	<main id="main">
		<div class="w1200 clearfix">
			<!-- main-contain start  -->
			<div class="main-contain">
				<!-- banner start -->
				<div class="banner">
					<ul class="pic">
						<li style="display:block;"><a href="javascript:void(0);"><img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537264084920&di=674290bae4e0f33ac252cff0ef95ec3f&imgtype=0&src=http%3A%2F%2Fpic1.win4000.com%2Fwallpaper%2F3%2F57a1548ddd149.jpg"
								 alt="test"></a></li>
						<li><a href="javascript:void(0);"><img src="https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2126622145,1468696620&fm=26&gp=0.jpg"
								 alt="test"></a></li>
						<li><a href="javascript:void(0);"><img src="https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2775064463,1890836574&fm=26&gp=0.jpg"
								 alt="test"></a></li>
						<li><a href="javascript:void(0);"><img src="https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=3182804019,3354432715&fm=26&gp=0.jpg"
								 alt="test"></a></li>
					</ul>
					<a href="javascript:void(0);" class="btn prev">
						<i class="PyWhich py-arrow-left"></i></a>
					<a href="javascript:void(0);" class="btn next">
						<i class="PyWhich py-arrow-right"></i></a>
					<ul class="tab">
						<li class="active"></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
				</div>
				<!-- banner end -->
				<!-- content start -->
				<div class="content">
					<!-- recommend-news start -->
					<ul class="recommend-news">
						<li>
							<a href="javascript:void(0);" target="_blank">
								<div class="recommend-thumbnail">
									<img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537264084300&di=8f55d3ddef645bd7de02024e63224cd3&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fblog%2F201506%2F09%2F20150609130218_cKEZm.jpeg" alt="title">
								</div>
								<p class="info">人生苦短，我用Python</p>
							</a>
						</li>
						<li>
							<a href="javascript:void(0);" target="_blank">
								<div class="recommend-thumbnail">
									<img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537264084300&di=8f55d3ddef645bd7de02024e63224cd3&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fblog%2F201506%2F09%2F20150609130218_cKEZm.jpeg" alt="title">
								</div>
								<p class="info">人生苦短，我用Python</p>
							</a>
						</li>
						<li>
							<a href="javascript:void(0);" target="_blank">
								<div class="recommend-thumbnail">
									<img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537264084300&di=8f55d3ddef645bd7de02024e63224cd3&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fblog%2F201506%2F09%2F20150609130218_cKEZm.jpeg" alt="title">
								</div>
								<p class="info">人生苦短，我用Python</p>
							</a>
						</li>
					</ul>
					<!-- recommend-news end -->
					<!--  news-nav start-->
					<nav class="news-nav">
						<ul class="clearfix">
							<li class="active"><a href="javascript:void(0)">最新资讯</a></li>

							<li><a href="javascript:void(0)" data-id="2">热点</a></li>
							<li><a href="javascript:void(0)" data-id="1">test</a></li>
						</ul>
					</nav>
					<!--  news-nav end -->
					<!-- news-contain start -->
					<div class="news-contain">
						<ul class="news-list">
							<li class="news-item">
								<a href="javascript:void(0);" class="news-thumbnail" target="_blank">
									<img src="http://onj3s3zfw.bkt.clouddn.com/o_1cn1sfjir1l2ln3erni1hne8d77.gif" alt="title" title="test1111">
								</a>
								<div class="news-content">
									<h4 class="news-title"><a href="javascript:void(0);">test1111</a></h4>
									<p class="news-details">test1111test1111test1111test1111test1111test1111</p>
									<div class="news-other">
										<span class="news-type">热点</span>
										<span class="news-time">刚刚</span>
										<span class="news-author">Admin</span>
									</div>
								</div>
							</li>
							<li class="news-item">
								<a href="javascript:void(0);" class="news-thumbnail" target="_blank">
									<img src="http://onj3s3zfw.bkt.clouddn.com/o_1cmq2acf9180h1rep142h1coa138d7.jpg" alt="title" title="新闻30">
								</a>
								<div class="news-content">
									<h4 class="news-title"><a href="javascript:void(0);">新闻30</a></h4>
									<p class="news-details">新闻描述30新闻描述30新闻描述30新闻描述30</p>
									<div class="news-other">
										<span class="news-type">test</span>
										<span class="news-time">5天前</span>
										<span class="news-author">Admin</span>
									</div>
								</div>
							</li>
						</ul>
					</div>
					<!-- news-contain end -->
					<!-- btn-more start -->
					<a href="javascript:void(0);" class="btn-more" id="btn-more" data-page="2">加载更多</a>
					<!-- btn-more end -->
				</div>
				<!-- content end -->
			</div>
			<!-- main-contain end -->
		  {% include 'base/side_base.html' %}
		</div>
	</main>
	<!-- main end -->
{% endblock %}

{% block script %}

{% endblock %}

templates/news/news_detail.html
{% extends 'base/base.html' %}
{% load new_filter %}
{% block title %}新闻详情页{% endblock %}
{% block style_link %}
    <link rel="stylesheet" href="/static/css/news/news_detail.css">
    <link rel="stylesheet" href="/static/css/news/con_right.css">
{% endblock %}

{% block mid_con %}
    <!-- main start -->
    <main id="main">
        <div class="w1200 clearfix">
            <!-- news-contain start  -->
            <div class="news-contain">
                <h1 class="news-title">{{ news.title }}</h1>
                <div class="news-info">
                    <div class="news-info-left">
                        <span class="news-author">{{ news.author.username}}</span>
                        <span class="news-pub-time">{{ new.add_time|date_format }}</span>
                        <span class="news-type">{{ news.tag.tag_name }}</span>
                    </div>
                </div>
                <article class="news-content">
                    {{ news.content|safe }}
                    <div style="height: 10px;"></div>
                    <img src="{{ news.photo_url }}">
                </article>
                <div class="comment-contain">
                    <div class="comment-pub clearfix">
                        <div class="new-comment">
                            文章评论(<span class="comment-count">0</span>)
                        </div>
                        {% if user.is_authenticated %}
                            <div class="comment-control logged-comment">
                                <input type="text" placeholder="请填写评论">
                            </div>
                        {% else %}
                            <div class="comment-control please-login-comment">
                                <input type="text" placeholder="请登录后参加评论" readonly>
                            </div>
                        {% endif %}
                        <button class="comment-btn" data-news-id="{{ news.id }}">发表评论</button>
                    </div>
                    <ul class="comment-list">
                        <li class="comment-item">

                        </li>
                    </ul>
                </div>
            </div>
            <!-- news-contain end  -->
            {% include 'base/con_right.html' %}
        </div>
    </main>
    <!-- main end -->
{% endblock %}
{% block script_link %}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="/static/js/base/common.js"></script>
    <script src="/static/js/news/news_detail.js"></script>
    <script src="/static/js/admin_staff/fsweetalert.js"></script>
    <script src="/static/js/admin_staff/sweetalert.min.js"></script>
    <script src="/static/js/base/message.js"></script>
{% endblock %}

templates/news/news_hot.html
{% extends 'admin_staff/base/admin_base.html' %}

{% block  title %}
    热门新闻管理页面
{% endblock %}

{% block style_link %}
    <link rel="stylesheet" href="/static/css/admin_staff/base/sweetalert.css">
{% endblock %}

{% block hedaer %}
    热门新闻管理页面
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <a href="{% url 'admin_staff:news_hot_add' %}" class="btn btn-primary pull-right"
                       id="btn-add-news-recommend">添加推荐新闻</a>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>新闻名称</th>
                            <th>新闻分类</th>
                            <th>优先级</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <div class="box-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}


{% block script_link %}
    <script src="/static/js/news/news_hot.js"></script>
    <script src="/static/js/base/common.js"></script>
    <script src="/static/js/admin_staff/sweetalert.min.js"></script>
    <script src="/static/js/admin_staff/fsweetalert.js"></script>
{% endblock %}

templates/news/search.html
{% extends 'base/base.html' %}
{% load new_filter %}
{% block title %}
    搜索页
{% endblock %}

{% block style_link %}
    <link rel="stylesheet" href="/static/css/news/search.css">
    <link rel="stylesheet" href="/static/css/news/con_right.css">
{% endblock %}

{% block mid_con %}
    <!-- main start -->
    <div class="mid-con">
        <main id="main">
            <div class="w1200 clearfix">
                <!-- main-contain start  -->
                <div class="main-contain ">
                    <!-- search-box start -->
                    <div class="search-box">
                        <form action="{% url 'news:search' %}" style="display: inline-flex;">
                            {% if q %}
                                <input type="search" placeholder="请输入要搜索的内容" name="q" class="search-control"
                                       value="{{ q }}">
                            {% else %}
                                <input type="search" placeholder="请输入要搜索的内容" name="q" class="search-control">
                            {% endif %}

                            <input type="submit" value="搜索" class="search-btn">
                        </form>
                        <!-- 可以用浮动 垂直对齐 以及 flex  -->
                    </div>
                    <!-- search-box end -->
                    <!-- content start -->
                    <div class="content">
                        <!-- search-list start -->
                        {% if ret_newses %}
                            <div class="search-result-list">
                                <h2 class="search-result-title">
                                    搜索结果 <span style="font-weight: 300;">{{ ret_newses.count }}</span>
                                </h2>
                                <ul class="news-list">
                                    {% for ret_news in ret_newses %}
                                        <li class="news-item clearfix">
                                            <a href="javascript:void(0);" class="news-thumbnail" target="_blank">
                                                <img src="{{ ret_news.photo_url }}">
                                            </a>
                                            <div class="news-content">
                                                <h4 class="news-title"><a
                                                        href="javascript:void(0);">{{ ret_news.title }}</a></h4>
                                                <p class="news-details">{{ ret_news.desc }}</p>
                                                <div class="news-other">
                                                    <span class="news-type">{{ ret_news.tag.name }}</span>
                                                    <span class="news-time">{{ ret_news.add_time|date_format }}</span>
                                                    <span class="news-author">{{ ret_news.author.username }}</span>
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}

                                </ul>
                            </div>
                        {% endif %}

                        <!-- search-list end -->
                        <!-- news-contain start -->
                        {% if hot_newses %}
                            <div class="news-contain">
                                <div class="hot-recommend-list">
                                    <h2 class="hot-recommend-title">热门推荐</h2>
                                    <ul class="news-list">
                                        {% for hot_news in hot_newses %}
                                            <li class="news-item clearfix">
                                                <a href="javascript:void(0);" class="news-thumbnail">
                                                    <img src="{{ hot_news.news.photo_url }}">
                                                </a>
                                                <div class="news-content">
                                                    <h4 class="news-title">
                                                        <a href="javascript:void(0);">{{ hot_news.news.title }}</a>
                                                    </h4>
                                                    <p class="news-details">
                                                    </p>
                                                    <div class="news-other">
                                                        <span class="news-type">{{ hot_news.news.tag.name }}</span>
                                                        <span class="news-time">{{ hot_news.news.add_time|date_format }}</span>
                                                        <span class="news-author">{{ hot_news.news.author.username }}</span>
                                                    </div>
                                                </div>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        {% endif %}

                        <!-- news-contain end -->
                    </div>
                    <!-- content end -->
                </div>
                <!-- main-contain  end -->
                {% include 'base/con_right.html' %}
            </div>
        </main>
    </div>>
    <!-- main end -->
{% endblock %}

{% block script_link %}

{% endblock %}